{% set version = "0.4.35" %}
{% set name = "jaxlib" %}

package:
  name: jaxlib
  version: {{ version }}

source:
  url: https://github.com/google/jax/archive/jax-v{{ version }}.tar.gz
  sha256: 65e086708ae56670676b7b2340ad82b901d8c9993d1241a839c8990bdb8d6212
  patches:
      - patches/0000-Consolidated-build-fixes-for-XLA.patch  # [not win]

build:
  number: 0
  # s390x is missing bazel.
  skip: true  # [s390x or py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang    # [win]
    - llvmdev  # [win]
    - lld      # [win]
    - python
    # https://github.com/jax-ml/jax/blob/jax-v0.4.35/build/build.py#L198
    - bazel >=6.5.0,<7
    - bazel-toolchain >=0.1.9  # [not win]
    - libabseil {{ libabseil }}
    - patch  # [not win]
    - libgrpc {{ libgrpc }}

  host:
    - python
    - pip
    - wheel
    - setuptools
    - numpy 2
    - python-build
    - libabseil {{ libabseil }}
    - openssl {{ openssl }}
    - nsync 1.24.0
    - snappy 1.2.1
    - double-conversion 3.1.5
    - jsoncpp 1.9.4
    - pybind11 2.13.6
    - libgrpc {{ libgrpc }}
    - libcurl {{ libcurl }}  # [not win]
    - zlib {{ zlib }}

  run:
    - python
    - numpy >=1.24
    - scipy >=1.10     # [py<312]
    - scipy >=1.11.1  # [py>=312]
    - ml_dtypes >=0.2.0
    - {{ pin_compatible('double-conversion', max_pin='x.x') }}
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
    - python
  commands:
    - pip check
    - python test_jaxlib.py
    - python -c 'import importlib.metadata; assert importlib.metadata.version("jaxlib") == "{{ version }}"'
  imports:
    - jaxlib
    - jaxlib.xla_client

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  description: |
    jaxlib is the support library for JAX. While JAX itself is a pure Python package, jaxlib contains the binary (C/C++) parts of the library, including Python bindings, the XLA compiler, the PJRT runtime, and a handful of handwritten kernels.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
