{% set version = "0.7.0" %}
{% set build = 0 %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  # only pull sources after upstream PyPI release...
  url: https://github.com/jax-ml/jax/archive/jax-v{{ version }}.tar.gz
  sha256: 518966801e4402667e77915c2dc7cf1a178a80e22ff253204a837f207a87fcde
  patches:
    - patches/0001-Allow-for-custom-CUDA-build.patch
    - patches/0002-Consolidated-build-fixes-for-XLA.patch
    - patches/0003-Add-missing-namespaces.patch

build:
  number: {{ build }}
  # https://github.com/jax-ml/jax?tab=readme-ov-file#supported-platforms
  skip: true  # [py<311]
  skip: true  # [cuda_compiler_version != "None" and aarch64]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - rsync                                  # [cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - unzip                    # [unix]
    - bazel 7.*
    - bazel-toolchain >=0.3.0  # [unix]
    # need protoc
    - libprotobuf
    # needs protoc-gen-grpc
    - libgrpc
    # needs flatc
    - flatbuffers <2.0.6
    # list libabseil here to ensure pinning correctly
    - libabseil
    - sed                      # [unix]
  host:
    {% if cuda_compiler_version != "None" %}
    - cuda-cudart-dev
    - cuda-cupti-dev
    - cuda-nvcc-tools
    - cuda-nvml-dev
    - cuda-nvtx-dev
    - cuda-version {{ cuda_compiler_version }}
    - cudnn
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    - nccl
    {% endif %}
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - python-build
    # list libabseil here to ensure pinning correctly
    - libabseil {{ libabseil }}
    - flatbuffers <2.0.6
    - grpc-bazel-rules {{ libgrpc }}
    - libgrpc {{ libgrpc }}
    - openssl {{ openssl }}
    - zlib {{ zlib }}
  run:
    - python
    - scipy >=1.12
    - numpy >=1.26
    - ml_dtypes >=0.5.0
    {% if cuda_compiler_version != "None" %}
    - __cuda
    - cuda-nvcc-tools
    # Workaround for https://github.com/conda-forge/jaxlib-feedstock/pull/288#issuecomment-2511925904
    - cuda-cupti-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
  imports:
    - jaxlib
    # Only this import actually triggers the load of XLA
    - jaxlib.xla_client
  commands:
    - pip check
    - python test_jaxlib.py
    # ensure that the package metadata did not mangle in the git hash, see #274
    - test -f $SP_DIR/jaxlib-{{ version }}.dist-info/METADATA

about:
  home: https://github.com/jax-ml/jax
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  description: |
    JAX is a Python library for accelerator-oriented array computation and program transformation, designed for 
    high-performance numerical computing and large-scale machine learning.
  dev_url: https://github.com/jax-ml/jax
  doc_url: https://github.com/jax-ml/jax/blob/main/README.md

extra:
  skip-lints:
    - deprecated_python_install_command
  recipe-maintainers:
    - ehfd
    - ericmjl
    - xhochy
    - ngam
    - h-vetinari
