{% set version = "0.1.71" %}
{% set name = "jaxlib" %}

package:
  name: jaxlib
  version: {{ version }}

source:
  url: https://github.com/google/jax/archive/{{ name }}-v{{ version }}.tar.gz
  sha256: 07a602e4e2e37fe46c17eeb6c25e80932f6abc5d1dde59e7868e7e3bb08f46c6
  patches:
    - 0001-Don-t-add-dashes-to-version.patch

build:
  number: 0
  skip: true  # [win or py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.18                           
    - scipy                                  # [build_platform != target_platform]
      # the build will download, compile and run its own bazel.
      # slow, but avoids problems with bazel transitively fetching
      # archives from non-existent mirrors.
      # - bazel 4.1.0
    - git
  host:
    - python
    - pip
    - numpy >=1.18
    - scipy
    - wheel
  run:
    - python
    - absl-py
    - {{ pin_compatible('numpy') }}
    - scipy
    - six

test:
  requires:
    - pip
    - python <3.10
  commands:
    - pip check
  imports:
    - jaxlib

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  description: |
    jaxlib is the support library for JAX. While JAX itself is a pure Python package, jaxlib contains the binary (C/C++) parts of the library, including Python bindings, the XLA compiler, the PJRT runtime, and a handful of handwritten kernels.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
  skip-lints:
    - missing_license_url
    - missing_doc_source_url
