{% set name = 'jaxlib' %}
{% set version = "0.7.2" %}
{% set build = 0 %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Only pull sources after upstream PyPI release
  url: https://github.com/jax-ml/jax/archive/jax-v{{ version }}.tar.gz
  sha256: 56d92604f1bb60bb3dbd7dc7c7dc21502d10b3474b8b905ce29ce06db6a26e45
  patches:
    - patches/0001-Allow-for-custom-CUDA-build.patch
    # Use vendored dependencies for packages depending on 'xla'
    - patches/0002-Consolidated-build-fixes-for-XLA.patch  # [unix]
    - patches/0003-avoid-mirror-that-doesn-t-seem-to-have-current-xla-a.patch
    - patches/0004-re-enable-use_fast_cpp_protos-true.patch

build:
  number: {{ build }}
  # https://github.com/jax-ml/jax?tab=readme-ov-file#supported-platforms
  skip: true  # [py<311]
  skip: true  # [cuda_compiler_version != "None" and aarch64]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}          # [cuda_compiler_version != "None"]
    - rsync                           # [cuda_compiler_version != "None"]
    - unzip                           # [unix]
    - bazel 7.*
    - bazel-toolchain >=0.4.0         # [unix]
    # need protoc
    - libprotobuf                     # [unix]
    # needs protoc-gen-grpc
    - libgrpc                         # [unix]
    # needs flatc
    - flatbuffers <2.0.6              # [unix]
    # list libabseil here to ensure pinning correctly
    - libabseil                       # [unix]
    - sed                             # [unix]
  host:
    {% if cuda_compiler_version != "None" %}
    - cuda-cudart-dev
    - cuda-cupti-dev
    - cuda-nvcc-tools
    - cuda-nvml-dev
    - cuda-nvtx-dev
    - cuda-version {{ cuda_compiler_version }}
    - cudnn
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    - nccl
    {% endif %}
    - python
    - pip
    - numpy >=2.0
    - setuptools
    - wheel
    - python-build
    # list libabseil here to ensure pinning correctly
    - libabseil {{ libabseil }}       # [unix]
    - flatbuffers <2.0.6              # [unix]
    - grpc-bazel-rules {{ libgrpc }}  # [unix]
    - libgrpc {{ libgrpc }}           # [unix]
    - openssl {{ openssl }}           # [unix]
    - zlib {{ zlib }}                 # [unix]
  run:
    # https://github.com/jax-ml/jax/blob/jax-v0.7.2/setup.py#L63
    - python
    - scipy >=1.13
    - numpy >=2.0
    - ml_dtypes >=0.5.0
    - opt_einsum
    {% if cuda_compiler_version != "None" %}
    - __cuda
    - cuda-nvcc-tools
    # Workaround for https://github.com/conda-forge/jaxlib-feedstock/pull/288#issuecomment-2511925904
    - cuda-cupti-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
  run_constrained:
    - jax >={{ version }}

test:
  requires:
    - pip
  files:
    - test_jaxlib.py
  imports:
    - jaxlib
    # Only this import actually triggers the load of XLA
    - jaxlib.xla_client
  commands:
    - pip check
    - python test_jaxlib.py
    # ensure that the package metadata did not mangle in the git hash, see #274
    - test -f $SP_DIR/jaxlib-{{ version }}.dist-info/METADATA  # [unix]
    - if not exist "%SP_DIR%\jaxlib-{{ version }}.dist-info\METADATA" exit 1  # [win]

about:
  home: https://github.com/jax-ml/jax
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Composable transformations of Python+NumPy programs - differentiate, vectorize, JIT to GPU/TPU, and more
  description: |
    JAX is a Python library for accelerator-oriented array computation and program transformation, designed for
    high-performance numerical computing and large-scale machine learning.
  dev_url: https://github.com/jax-ml/jax
  doc_url: https://github.com/jax-ml/jax/blob/main/README.md

extra:
  skip-lints:
    - deprecated_python_install_command
  recipe-maintainers:
    - ehfd
    - ericmjl
    - xhochy
    - ngam
    - h-vetinari
