{% set version = "0.4.35" %}
{% set name = "jaxlib" %}

{% set build = 0 %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  url: https://github.com/google/jax/archive/jax-v{{ version }}.tar.gz
  sha256: 65e086708ae56670676b7b2340ad82b901d8c9993d1241a839c8990bdb8d6212
  patches:
      - patches/0000-Consolidated-build-fixes-for-XLA.patch  # [not win]

build:
  number: {{ build }}
  # s390x is missing bazel.
  skip: true  # [s390x or py<310]
  skip: true  # [cuda_compiler != "None" and aarch64]
  skip: true  # [cuda_compiler != "None" and win]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}              # [cuda_compiler_version != "None"]
    - clang    # [win]
    - llvmdev  # [win]
    - lld      # [win]
    - python
    # https://github.com/jax-ml/jax/blob/jax-v0.4.35/build/build.py#L198
    - bazel >=6.5.0,<7
    - bazel-toolchain >=0.1.9  # [not win]
    - libabseil
    - patch  # [not win]
    - libprotobuf
    - libgrpc

  host:
    - cudnn             # [cuda_compiler_version != "None"]
    - nccl              # [cuda_compiler_version != "None"]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-cupti-dev    # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvml-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvtx-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvcc-tools  # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
    - python
    - pip
    - wheel
    - setuptools
    - numpy 1.22.*  # [py<311]
    - numpy 1.23.*  # [py==311]
    - numpy 1.26.*  # [py>=312]
    - python-build
    - libabseil 20240116.2
    - openssl 3.0.15
    - nsync 1.24.0
    - snappy 1.2.1
    - double-conversion 3.1.5
    - jsoncpp 1.9.4
    - pybind11 2.13.6
    - re2 2022.04.01
    - libgrpc 1.62.2
    - libcurl 8.9.1  # [not win]
    - zlib 1.2.13
    - libprotobuf

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.10     # [py<312]
    - scipy >=1.11.1  # [py>=312]
    - ml_dtypes >=0.2.0
    - double-conversion
    - __cuda  # [cuda_compiler_version != "None"]
    - cuda-nvcc-tools  # [(cuda_compiler_version or "").startswith("12")]
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
    - python
  commands:
    - pip check
    - python test_jaxlib.py
  imports:
    - jaxlib
    - jaxlib.xla_client

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  description: |
    jaxlib is the support library for JAX. While JAX itself is a pure Python package, jaxlib contains the binary (C/C++) parts of the library, including Python bindings, the XLA compiler, the PJRT runtime, and a handful of handwritten kernels.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
