{% set version = "0.3.25" %}
{% set name = "jaxlib" %}

package:
  name: jaxlib
  version: {{ version }}

source:
  url: https://github.com/google/jax/archive/{{ name }}-v{{ version }}.tar.gz
  sha256: 73ebc7868631cd9d520385557bbd7f08762d748a5a6a1bebef0f3b8d7ba748ef

build:
  number: 3
  # ppc64le and s390x are missing bazel. Win not supported by jaxlib.
  skip: true  # [ppc64le or s390x or win or py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    # https://github.com/google/jax/blob/jaxlib-v0.3.25/build/build.py#L197
    - bazel >=5.1.1

  host:
    - python
    - pip
    - wheel
    - setuptools
    - numpy 1.21.*  # [py<311]
    - numpy 1.23.*  # [py>=311]

  run:
    - python
    - numpy >=1.21,<2  # [py<311]
    - numpy >=1.21,<2  # [py>=311]
    - scipy >=1.5
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
    - python
  commands:
    - pip check
    - python test_jaxlib.py
  imports:
    - jaxlib
    - jaxlib.xla_client

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  description: |
    jaxlib is the support library for JAX. While JAX itself is a pure Python package, jaxlib contains the binary (C/C++) parts of the library, including Python bindings, the XLA compiler, the PJRT runtime, and a handful of handwritten kernels.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
  skip-lints:
    - missing_license_url
    - missing_doc_source_url
